In [2]:
# 导入必要的库
import lightgbm as lgb
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [3]:
from sklearn import datasets

iris = datasets.load_iris()
features = iris.data
target = iris.target
print(features.shape, target.shape)
print(iris.feature_names)

(150, 4) (150,)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
type(features)

numpy.ndarray

In [6]:
features.data

In [7]:
    features.all

<function ndarray.all>

In [8]:
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

# 创建一个示例数据集
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

# Z-Score标准化
zscore_scaler = StandardScaler()
zscore_scaled_data = zscore_scaler.fit_transform(data)
print("Z-Score标准化后的数据：")
print(zscore_scaled_data)

# Min-Max标准化
minmax_scaler = MinMaxScaler()
minmax_scaled_data = minmax_scaler.fit_transform(data)
print("\nMin-Max标准化后的数据：")
print(minmax_scaled_data)

# Robust标准化
robust_scaler = RobustScaler()
robust_scaled_data = robust_scaler.fit_transform(data)
print("\nRobust标准化后的数据：")
print(robust_scaled_data)

Z-Score标准化后的数据：
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

Min-Max标准化后的数据：
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]

Robust标准化后的数据：
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]


In [ ]:
# 加载示例数据集（可以替换为您自己的数据集）
data = pd.read_csv('your_dataset.csv')
X = data.drop('target_column', axis=1)  # 特征数据
y = data['target_column']  # 目标数据

# 将数据拆分为训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 创建LightGBM数据集
train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

# 设置LightGBM参数
params = {
    'objective': 'regression',  # 选择回归任务
    'metric': 'rmse',  # 评估指标为均方根误差
    'boosting_type': 'gbdt',  # 使用梯度提升决策树
    'num_leaves': 31,  # 决策树的叶子节点数
    'learning_rate': 0.05,  # 学习率
    'feature_fraction': 0.9,  # 每次迭代中随机选择特征的比例
    'bagging_fraction': 0.8,  # 每次迭代中随机选择数据的比例
    'bagging_freq': 5,  # bagging的频率
    'verbose': 0  # 显示训练过程
}

# 训练LightGBM模型
num_round = 100  # 迭代次数
bst = lgb.train(params, train_data, num_round, valid_sets=[test_data], early_stopping_rounds=10)

# 预测
y_pred = bst.predict(X_test, num_iteration=bst.best_iteration)

# 评估模型性能（均方根误差）
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f'均方根误差 (RMSE): {rmse}')

# 可以根据需要保存和加载模型
# bst.save_model('lgb_model.txt')
# bst = lgb.Booster(model_file='lgb_model.txt')


In [ ]:
pd.to_numeric(df["column_name"], errors='coerce').fillna(0).astype(int)

In [280]:
import pandas as pd
# 导入必要的库
import lightgbm as lgb
from sklearn.model_selection import train_test_split

In [288]:
df = pd.read_csv(r'C:\Users\Polo\Desktop\dw_casl_user_sample_feature.csv')

C:\Users\Polo\AppData\Local\Temp\ipykernel_30292\2233142213.py:1: DtypeWarning: Columns (4,5,6,12,13,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r'C:\Users\Polo\Desktop\dw_casl_user_sample_feature.csv')


In [289]:
# 空值处理
df = df.drop(['msisdn', 'imsi'], axis=1)  #删除加密的特征
df.loc[df['is_comm_user'] == r'\N', 'is_comm_user'] = None  #是否为移动用户\N置为空值
df.loc[df['is_init_comm_user'] == r'\N', 'is_init_comm_user'] = None  #是否主动通信用户\N置为空值
df.loc[df['cust_star'] == r'\N', 'cust_star'] = None  #客户星级\N置为空值
df.loc[df['dome_roam_flux_days'] == r'\N', 'dome_roam_flux_days'] = None  #省际漫游流量天数\N置为空值
df.loc[df['inter_roam_flux_days'] == r'\N', 'inter_roam_flux_days'] = None  #国际漫游流量天数\N置为空值
df.loc[df['idcard_birth_area'] == r'\N', 'idcard_birth_area'] = None  #身份证出生地\N置为空值
df['dou'].fillna(0, inplace=True)  #使用流量为空值的默认为0
df['is_comm_user'].fillna(0, inplace=True)  #是否为移动用户的空值默认为0
df['is_init_comm_user'].fillna(0, inplace=True)  #是否主动通信用户的空值默认为0
df['cust_star'].fillna(0, inplace=True)  #客户星级的空值默认为0
df['vip_cust_id'].fillna(0, inplace=True)  #重要客户标识的空值默认为0
df['dome_roam_flux_days'].fillna(int(df[df['dome_roam_flux_days'].notnull()]['dome_roam_flux_days'].astype(int).mean()),
                                 inplace=True)  #省际漫游流量天数填充为平均值
df['inter_roam_flux_days'].fillna(
    int(df[df['inter_roam_flux_days'].notnull()]['inter_roam_flux_days'].astype(int).mean()),
    inplace=True)  #国际漫游流量天数填充为平均值
df.drop(df[df['mage_status'] == r"\N"].index, inplace=True)  # 删除mage_status等于\N的35行
df.drop(df[df['educat_degree_code'] == r"\N"].index, inplace=True)  # 删除educat_degree_code等于\N的35行
df.drop(df[df['ocpn_code'] == r"\N"].index, inplace=True)  # 删除ocpn_code等于\N的35行
df.drop(df[df['idcard_birth_area'].isnull()].index, inplace=True)  #删除身份证出生地为空值的496个数据

In [290]:
# 时间处理
df1 = pd.to_datetime(df['month'], format="%Y%m")
df['year'] = df1.dt.year
df['month'] = df1.dt.month
df = pd.get_dummies(df, columns=['month'], dtype=int)  # 时间独热编码
df = df.astype(int)  #类型转换

In [293]:
# 训练集&测试集创建
x = df.drop('sample_flag', axis=1)  # 特征数据
y = df['sample_flag']  # 目标数据
# 将数据拆分为训练集和测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# 创建LightGBM数据集
train_data = lgb.Dataset(x_train, label=y_train)
test_data = lgb.Dataset(x_test, label=y_test, reference=train_data)

In [295]:
# 训练模型&评分标准
from sklearn.metrics import roc_auc_score

# 设置LightGBM参数
params = {
    'cat_smooth': 8,
    'is_unbalance': True,
    'max_depth': 9,
    'metric': ['binary_logloss', 'auc'],
    'min_child_samples': 22,
    'num_iterations': 200,
    'num_leaves': 100,
    'objective': 'binary',
    'reg_alpha': 0.01,
    'reg_lambda': 8,
    'early_stopping_rounds': 10
}

# 训练模型
model = lgb.train(params, train_data, valid_sets=[test_data])

print(model.best_iteration)
model.save_model('1.pkl')
# 预测
y_pred = model.predict(x_test, num_iteration=model.best_iteration)

# 评估模型性能
auc = roc_auc_score(y_test, y_pred)

print(f'AUC: {auc}')

D:\pycharm project\Internet-of-Vehicles-Collision-Recognition\venv\lib\site-packages\lightgbm\engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


[LightGBM] [Info] Number of positive: 26237, number of negative: 134210
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007539 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 968
[LightGBM] [Info] Number of data points in the train set: 160447, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.163524 -> initscore=-1.632235
[LightGBM] [Info] Start training from score -1.632235
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[6]	valid_0's binary_logloss: 0.37592	valid_0's auc: 0.871235
6
AUC: 0.8712353690384872


In [2]:
import pandas as pd

re = pd.read_csv(
    r'D:\huancun\WeChat Files\wxid_7fjwgckpy7m522\FileStorage\File\2023-09\dw_casl_user_sample_feature_all.csv')

C:\Users\Polo\AppData\Local\Temp\ipykernel_18056\70266967.py:2: DtypeWarning: Columns (3,4,5,15) have mixed types. Specify dtype option on import or set low_memory=False.
  re=pd.read_csv(r'D:\huancun\WeChat Files\wxid_7fjwgckpy7m522\FileStorage\File\2023-09\dw_casl_user_sample_feature_all.csv')


In [3]:
re.head(10)

sample_flag                                id  prov_id mage_status  \
0            1  d22dc3132106e63d0f529c19694dcf9e    11700           1   
1            1  d22dc3132106e63d0f529c19694dcf9e    11700           1   
2            0  47721b2ed7cdb28c65cc272503902140    11700           0   
3            0  86f67ae187fef1822e4003a169ddfe1b    10900           3   
4            0  61e39e03d105ef3b86510f43b4754562    12300           3   
5            0  88e00c3063043cc3d3f697e92ea9a90d    12300           3   
6            0  6cb989a68b90baec2710b4250b23e9af    11400           3   
7            0  90fc4da11c8a22dc8f0458d14856362a    11000           2   
8            0  3fbfa5da3cae1296168f8188c5c9d43a    10300           3   
9            0  b4cbc68ac44fba9bdc608160e9763387    12000           3   

  ocpn_code educat_degree_code  age_level  sex  cm_cons_tot_amt  innet_dura  \
0        01                 01          5    1                8          44   
1        01                 01          5    1                8          46   
2        99                 99          3    2               31           4   
3        99                 01          9    1                5          56   
4        99                 01          5    1               11          19   
5        99                 01          8    2                4           3   
6        99                 01          6    2                6         116   
7        03                 01          7    1               12          54   
8        99                 01          6    2                6          27   
9        99                 01         10    1                9          12   

   ...  avg_6m_111003_click_cnt avg_6m_111003_app_cnt avg_6m_111003_flux_all  \
0  ...                    55.00                  0.17                6846.49   
1  ...                    20.83                  0.67                2002.62   
2  ...                     0.00                  0.00                   0.00   
3  ...                     0.50                  0.33                  56.85   
4  ...                     0.33                  0.17                   0.12   
5  ...                     0.00                  0.00                   0.00   
6  ...                   554.50                  1.67               13807.68   
7  ...                     0.00                  0.00                   0.00   
8  ...                    28.67                  1.33                 780.10   
9  ...                     0.17                  0.17                   0.12   

  avg_6m_112002_click_cnt  avg_6m_112002_app_cnt avg_6m_112002_flux_all  \
0                   10.83                   0.50                 618.07   
1                    4.00                   0.50                  95.66   
2                    0.00                   0.00                   0.00   
3                  169.33                   0.83                8345.32   
4                    1.50                   0.50                   4.31   
5                    0.00                   0.00                   0.00   
6                  193.83                   2.50                4992.07   
7                    6.67                   0.83                 146.70   
8                   97.33                   1.50                4058.60   
9                   27.00                   7.33                   9.73   

   avg_6m_107004_click_cnt  avg_6m_107004_app_cnt  avg_6m_107004_flux_all  \
0                     0.00                   0.00                    0.00   
1                     0.00                   0.00                    0.00   
2                     0.00                   0.00                    0.00   
3                     7.83                   1.00                   59.54   
4                     0.00                   0.00                    0.00   
5                     0.00                   0.00                    0.00   
6                     0.17                   0.17                  120.38   
7     

In [17]:
import lightgbm as lgb
import pandas as pd


def data_deal(df):
    # 空值处理
    df = df.drop(['id'], axis=1)  # 删除加密的特征
    df.loc[df['is_comm_user'] == r'\N', 'is_comm_user'] = None  # 是否为移动用户\N置为空值
    df.loc[df['is_init_comm_user'] == r'\N', 'is_init_comm_user'] = None  # 是否主动通信用户\N置为空值
    df.loc[df['cust_star'] == r'\N', 'cust_star'] = None  # 客户星级\N置为空值
    df.loc[df['dome_roam_flux_days'] == r'\N', 'dome_roam_flux_days'] = None  # 省际漫游流量天数\N置为空值
    df.loc[df['inter_roam_flux_days'] == r'\N', 'inter_roam_flux_days'] = None  # 国际漫游流量天数\N置为空值
    df.loc[df['idcard_birth_area'] == r'\N', 'idcard_birth_area'] = None  # 身份证出生地\N置为空值
    df['dou'].fillna(0, inplace=True)  # 使用流量为空值的默认为0
    df['is_comm_user'].fillna(0, inplace=True)  # 是否为移动用户的空值默认为0
    df['is_init_comm_user'].fillna(0, inplace=True)  # 是否主动通信用户的空值默认为0
    df['cust_star'].fillna(0, inplace=True)  # 客户星级的空值默认为0
    df['vip_cust_id'].fillna(0, inplace=True)  # 重要客户标识的空值默认为0
    df['dome_roam_flux_days'].fillna(
        int(df[df['dome_roam_flux_days'].notnull()]['dome_roam_flux_days'].astype(int).mean()),
        inplace=True)  # 省际漫游流量天数填充为平均值
    df['inter_roam_flux_days'].fillna(
        int(df[df['inter_roam_flux_days'].notnull()]['inter_roam_flux_days'].astype(int).mean()),
        inplace=True)  # 国际漫游流量天数填充为平均值
    df.drop(df[df['mage_status'] == r"\N"].index, inplace=True)  # 删除mage_status等于\N的35行
    df.drop(df[df['educat_degree_code'] == r"\N"].index, inplace=True)  # 删除educat_degree_code等于\N的35行
    df.drop(df[df['ocpn_code'] == r"\N"].index, inplace=True)  # 删除ocpn_code等于\N的35行
    df.drop(df[df['idcard_birth_area'].isnull()].index, inplace=True)  # 删除身份证出生地为空值的496个数据

    # 时间处理
    df1 = pd.to_datetime(df['month'], format="%Y%m")
    df['year'] = df1.dt.year
    df['month'] = df1.dt.month
    df = pd.get_dummies(df, columns=['month'], dtype=int)  # 时间独热编码
    df = df.astype(int)  # 类型转换
    return df


df = pd.read_csv(
    r'D:\huancun\WeChat Files\wxid_7fjwgckpy7m522\FileStorage\File\2023-09\dw_casl_user_sample_feature_all.csv')
df = data_deal(df)

model = lgb.Booster(model_file='../SL.pkl')
# 预测
y_pred = model.predict(df, num_iteration=model.best_iteration)
df['sample_flag'] = y_pred
df.to_csv('dw_casl_user_sample_feature_result.csv', index=False)

C:\Users\Polo\AppData\Local\Temp\ipykernel_25196\532435699.py:38: DtypeWarning: Columns (3,4,5,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(


prov_id  mage_status  ocpn_code  educat_degree_code  age_level  sex  \
0       11700            1          1                   1          5    1   
1       11700            1          1                   1          5    1   
2       11700            0         99                  99          3    2   
3       10900            3         99                   1          9    1   
4       12300            3         99                   1          5    1   
...       ...          ...        ...                 ...        ...  ...   
996     11000            2          1                   1          6    2   
997     10200            3         99                   3          7    1   
998     10100            3         99                   1         13    2   
999     12300            3         99                   1         10    2   
1000    12300            2         99                   1          6    1   

      cm_cons_tot_amt  innet_dura     dou  is_comm_user  ...  month_2  \
0                   8          44   41002             1  ...        0   
1                   8          46   17558             1  ...        0   
2                  31           4       0             0  ...        0   
3                   5          56   20176             1  ...        0   
4                  11          19     481             0  ...        0   
...               ...         ...     ...           ...  ...      ...   
996                 6          76   11171             1  ...        0   
997                14          62  118307             1  ...        0   
998                 3         123       0             1  ...        0   
999                 5         169    2525             1  ...        0   
1000               11         116   29220             1  ...        0   

      month_3  month_4  month_7  month_8  month_9  month_10  month_11  \
0           0        0        0        1        0         0         0   
1           0        0        0        0        0         1         0   
2           0        0        0        0        1         0         0   
3           0        0        0        0        0         1         0   
4           0        0        0        1        0         0         0   
...       ...      ...      ...      ...      ...       ...       ...   
996         0        0        0        0        0         0         0   
997         0        0        0        0        0         0         1   
998         0        0        0        0        0         1         0   
999         0        0        0        1        0         0         0   
1000        1        0        0        0        0         0         0   

      month_12  sample_flag  
0            0     0.710151  
1            0     0.937227  
2            0     0.000315  
3            0     0.002864  
4            0     0.001740  
...        ...          ...  
996          1     0.948702  
997          0     0.687465  
998          0     0.014946  
999          0     0.008670  
1000         0     0.545710  

[1000 rows x 78 columns]

In [15]:
y_pred

array([7.10150517e-01, 9.37227031e-01, 3.14516116e-04, 2.86441238e-03,
       1.73981519e-03, 2.67836017e-03, 5.74432033e-01, 5.63214697e-02,
       2.77788734e-01, 4.30331922e-03, 4.28938087e-03, 6.48753090e-02,
       4.00770233e-01, 3.66474886e-03, 9.37925829e-04, 3.01409624e-01,
       1.01435402e-02, 2.86733125e-04, 1.34629270e-02, 7.61042456e-03,
       1.44487629e-02, 9.49810906e-01, 7.38858577e-01, 3.72054287e-03,
       1.47035315e-01, 1.69783405e-03, 7.25256026e-02, 2.25721478e-01,
       5.81509027e-02, 2.88710815e-03, 6.67480071e-01, 5.38428100e-01,
       2.53200580e-03, 1.10294921e-02, 9.40338527e-02, 7.78955255e-02,
       1.42179282e-02, 1.08526092e-03, 8.38879798e-02, 3.71840503e-02,
       1.81189688e-02, 4.95787477e-02, 6.37479405e-03, 2.12678202e-02,
       2.86886488e-02, 2.57339278e-02, 1.02972139e-01, 1.60829284e-02,
       1.96961403e-02, 2.32439015e-01, 4.23104459e-02, 7.61396519e-01,
       3.40358868e-03, 2.54598337e-02, 1.60557015e-02, 6.27230841e-01,
      

In [20]:
df = pd.read_csv(
    r'D:\huancun\WeChat Files\wxid_7fjwgckpy7m522\FileStorage\File\2023-09\dw_casl_user_sample_feature_all.csv')
df.dtypes

C:\Users\Polo\AppData\Local\Temp\ipykernel_25196\345166561.py:1: DtypeWarning: Columns (3,4,5,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(


sample_flag                  int64
id                          object
prov_id                      int64
mage_status                 object
ocpn_code                   object
                            ...   
avg_6m_112002_flux_all     float64
avg_6m_107004_click_cnt    float64
avg_6m_107004_app_cnt      float64
avg_6m_107004_flux_all     float64
month                        int64
Length: 69, dtype: object

In [22]:

df = pd.read_csv(
    r'D:\huancun\WeChat Files\wxid_7fjwgckpy7m522\FileStorage\File\2023-09\dw_casl_user_sample_feature_all.csv')
# 空值处理
df.loc[df['is_comm_user'] == r'\N', 'is_comm_user'] = None  # 是否为移动用户\N置为空值
df.loc[df['is_init_comm_user'] == r'\N', 'is_init_comm_user'] = None  # 是否主动通信用户\N置为空值
df.loc[df['cust_star'] == r'\N', 'cust_star'] = None  # 客户星级\N置为空值
df.loc[df['dome_roam_flux_days'] == r'\N', 'dome_roam_flux_days'] = None  # 省际漫游流量天数\N置为空值
df.loc[df['inter_roam_flux_days'] == r'\N', 'inter_roam_flux_days'] = None  # 国际漫游流量天数\N置为空值
df.loc[df['idcard_birth_area'] == r'\N', 'idcard_birth_area'] = None  # 身份证出生地\N置为空值
df['dou'].fillna(0, inplace=True)  # 使用流量为空值的默认为0
df['is_comm_user'].fillna(0, inplace=True)  # 是否为移动用户的空值默认为0
df['is_init_comm_user'].fillna(0, inplace=True)  # 是否主动通信用户的空值默认为0
df['cust_star'].fillna(0, inplace=True)  # 客户星级的空值默认为0
df['vip_cust_id'].fillna(0, inplace=True)  # 重要客户标识的空值默认为0
df['dome_roam_flux_days'].fillna(int(df[df['dome_roam_flux_days'].notnull()]['dome_roam_flux_days'].astype(int).mean()),
                                 inplace=True)  # 省际漫游流量天数填充为平均值
df['inter_roam_flux_days'].fillna(
    int(df[df['inter_roam_flux_days'].notnull()]['inter_roam_flux_days'].astype(int).mean()),
    inplace=True)  # 国际漫游流量天数填充为平均值
df.drop(df[df['mage_status'] == r"\N"].index, inplace=True)  # 删除mage_status等于\N的35行
df.drop(df[df['educat_degree_code'] == r"\N"].index, inplace=True)  # 删除educat_degree_code等于\N的35行
df.drop(df[df['ocpn_code'] == r"\N"].index, inplace=True)  # 删除ocpn_code等于\N的35行
df.drop(df[df['idcard_birth_area'].isnull()].index, inplace=True)  # 删除身份证出生地为空值的496个数据

# 时间处理
df1 = pd.to_datetime(df['month'], format="%Y%m")
df['year'] = df1.dt.year
df['month'] = df1.dt.month
df = pd.get_dummies(df, columns=['month'], dtype=int)  # 时间独热编码
df_id = df['id']
df=df.drop(['id'],axis=1)
df = df.astype(float)  # 类型转换

C:\Users\Polo\AppData\Local\Temp\ipykernel_25196\3619377424.py:1: DtypeWarning: Columns (3,4,5,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(


In [23]:
df.dtypes

sample_flag           float64
prov_id               float64
mage_status           float64
ocpn_code             float64
educat_degree_code    float64
                       ...   
month_8               float64
month_9               float64
month_10              float64
month_11              float64
month_12              float64
Length: 78, dtype: object

In [24]:
df

sample_flag  prov_id  mage_status  ocpn_code  educat_degree_code  \
0               1.0  11700.0          1.0        1.0                 1.0   
1               1.0  11700.0          1.0        1.0                 1.0   
2               0.0  11700.0          0.0       99.0                99.0   
3               0.0  10900.0          3.0       99.0                 1.0   
4               0.0  12300.0          3.0       99.0                 1.0   
...             ...      ...          ...        ...                 ...   
200345          0.0  10900.0          3.0       99.0                 1.0   
200346          1.0  11100.0          3.0       99.0                 1.0   
200347          0.0  12400.0          3.0       99.0                 3.0   
200348          0.0  12400.0          3.0       99.0                 3.0   
200349          0.0  11400.0          3.0       99.0                 1.0   

        age_level  sex  cm_cons_tot_amt  innet_dura      dou  ...  month_1  \
0             5.0  1.0              8.0        44.0  41002.0  ...      0.0   
1             5.0  1.0              8.0        46.0  17558.0  ...      0.0   
2             3.0  2.0             31.0         4.0      0.0  ...      0.0   
3             9.0  1.0              5.0        56.0  20176.0  ...      0.0   
4             5.0  1.0             11.0        19.0    481.0  ...      0.0   
...           ...  ...              ...         ...      ...  ...      ...   
200345        5.0  1.0              2.0        17.0   1260.0  ...      0.0   
200346        6.0  2.0              4.0       110.0   2366.0  ...      0.0   
200347        6.0  1.0              4.0       117.0     32.0  ...      1.0   
200348        6.0  1.0              4.0       117.0     32.0  ...      1.0   
200349       13.0  1.0              3.0       117.0      5.0  ...      0.0   

        month_2  month_3  month_4  month_7  month_8  month_9  month_10  \
0           0.0      0.0      0.0      0.0      1.0      0.0       0.0   
1           0.0      0.0      0.0      0.0      0.0      0.0       1.0   
2           0.0      0.0      0.0      0.0      0.0      1.0       0.0   
3           0.0      0.0      0.0      0.0      0.0      0.0       1.0   
4           0.0      0.0      0.0      0.0      1.0      0.0       0.0   
...         ...      ...      ...      ...      ...      ...       ...   
200345      0.0      0.0      0.0      0.0      0.0      0.0       0.0   
200346      0.0      0.0      0.0      0.0      0.0      0.0       1.0   
200347      0.0      0.0      0.0      0.0      0.0      0.0       0.0   
200348      0.0      0.0      0.0      0.0      0.0      0.0       0.0   
200349      0.0      0.0      0.0      0.0      1.0      0.0       0.0   

        month_11  month_12  
0            0.0       0.0  
1            0.0       0.0  
2            0.0       0.0  
3            0.0       0.0  
4            0.0       0.0  
...          ...       ...  
200345       0.0       1.0  
200346       0.0       0.0  
200347       0.0       0.0  
200348       0.0       0.0  
200349       0.0       0.0  

[199854 rows x 78 columns]