In [2]:
# 导入必要的库
import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error

In [3]:
from sklearn import datasets
import matplotlib.pyplot as plt

iris = datasets.load_iris()
features = iris.data
target = iris.target
print(features.shape,target.shape)
print(iris.feature_names)

(150, 4) (150,)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
type(features)

numpy.ndarray

In [6]:
features.data

In [7]:
    features.all

<function ndarray.all>

In [8]:
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

# 创建一个示例数据集
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

# Z-Score标准化
zscore_scaler = StandardScaler()
zscore_scaled_data = zscore_scaler.fit_transform(data)
print("Z-Score标准化后的数据：")
print(zscore_scaled_data)

# Min-Max标准化
minmax_scaler = MinMaxScaler()
minmax_scaled_data = minmax_scaler.fit_transform(data)
print("\nMin-Max标准化后的数据：")
print(minmax_scaled_data)

# Robust标准化
robust_scaler = RobustScaler()
robust_scaled_data = robust_scaler.fit_transform(data)
print("\nRobust标准化后的数据：")
print(robust_scaled_data)

Z-Score标准化后的数据：
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

Min-Max标准化后的数据：
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]

Robust标准化后的数据：
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]


In [ ]:
# 加载示例数据集（可以替换为您自己的数据集）
data = pd.read_csv('your_dataset.csv')
X = data.drop('target_column', axis=1)  # 特征数据
y = data['target_column']  # 目标数据

# 将数据拆分为训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 创建LightGBM数据集
train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

# 设置LightGBM参数
params = {
    'objective': 'regression',  # 选择回归任务
    'metric': 'rmse',  # 评估指标为均方根误差
    'boosting_type': 'gbdt',  # 使用梯度提升决策树
    'num_leaves': 31,  # 决策树的叶子节点数
    'learning_rate': 0.05,  # 学习率
    'feature_fraction': 0.9,  # 每次迭代中随机选择特征的比例
    'bagging_fraction': 0.8,  # 每次迭代中随机选择数据的比例
    'bagging_freq': 5,  # bagging的频率
    'verbose': 0  # 显示训练过程
}

# 训练LightGBM模型
num_round = 100  # 迭代次数
bst = lgb.train(params, train_data, num_round, valid_sets=[test_data], early_stopping_rounds=10)

# 预测
y_pred = bst.predict(X_test, num_iteration=bst.best_iteration)

# 评估模型性能（均方根误差）
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f'均方根误差 (RMSE): {rmse}')

# 可以根据需要保存和加载模型
# bst.save_model('lgb_model.txt')
# bst = lgb.Booster(model_file='lgb_model.txt')


In [ ]:
pd.to_numeric(df["column_name"], errors='coerce').fillna(0).astype(int)

In [280]:
import pandas as pd
# 导入必要的库
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error

In [288]:
df=pd.read_csv(r'C:\Users\Polo\Desktop\dw_casl_user_sample_feature.csv')

C:\Users\Polo\AppData\Local\Temp\ipykernel_30292\2233142213.py:1: DtypeWarning: Columns (4,5,6,12,13,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r'C:\Users\Polo\Desktop\dw_casl_user_sample_feature.csv')


In [289]:
# 空值处理
df=df.drop(['msisdn','imsi'],axis=1)#删除加密的特征
df.loc[df['is_comm_user'] == r'\N', 'is_comm_user'] = None#是否为移动用户\N置为空值
df.loc[df['is_init_comm_user'] == r'\N', 'is_init_comm_user'] = None#是否主动通信用户\N置为空值
df.loc[df['cust_star'] == r'\N', 'cust_star'] = None#客户星级\N置为空值
df.loc[df['dome_roam_flux_days'] == r'\N', 'dome_roam_flux_days'] = None#省际漫游流量天数\N置为空值
df.loc[df['inter_roam_flux_days'] == r'\N', 'inter_roam_flux_days'] = None#国际漫游流量天数\N置为空值
df.loc[df['idcard_birth_area'] == r'\N', 'idcard_birth_area'] = None#身份证出生地\N置为空值
df['dou'].fillna(0,inplace=True) #使用流量为空值的默认为0
df['is_comm_user'].fillna(0,inplace=True)#是否为移动用户的空值默认为0
df['is_init_comm_user'].fillna(0,inplace=True)#是否主动通信用户的空值默认为0
df['cust_star'].fillna(0,inplace=True)#客户星级的空值默认为0
df['vip_cust_id'].fillna(0,inplace=True)#重要客户标识的空值默认为0
df['dome_roam_flux_days'].fillna(int(df[df['dome_roam_flux_days'].notnull()]['dome_roam_flux_days'].astype(int).mean()),inplace=True)#省际漫游流量天数填充为平均值
df['inter_roam_flux_days'].fillna(int(df[df['inter_roam_flux_days'].notnull()]['inter_roam_flux_days'].astype(int).mean()),inplace=True)#国际漫游流量天数填充为平均值
df.drop(df[df['mage_status'] == r"\N"].index, inplace=True)# 删除mage_status等于\N的35行
df.drop(df[df['educat_degree_code'] == r"\N"].index, inplace=True)# 删除educat_degree_code等于\N的35行
df.drop(df[df['ocpn_code'] == r"\N"].index, inplace=True)# 删除ocpn_code等于\N的35行
df.drop(df[df['idcard_birth_area'].isnull()].index, inplace=True)#删除身份证出生地为空值的496个数据

In [290]:
# 时间处理
df1=pd.to_datetime(df['month'], format="%Y%m")
df['year'] = df1.dt.year
df['month'] = df1.dt.month
df=pd.get_dummies(df, columns=['month'], dtype=int)# 时间独热编码
df=df.astype(int)#类型转换

In [293]:
# 训练集&测试集创建
x = df.drop('sample_flag', axis=1)  # 特征数据
y = df['sample_flag']  # 目标数据
# 将数据拆分为训练集和测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# 创建LightGBM数据集
train_data = lgb.Dataset(x_train, label=y_train)
test_data = lgb.Dataset(x_test, label=y_test, reference=train_data)

In [295]:
# 训练模型&评分标准
from sklearn.metrics import roc_auc_score

# 设置LightGBM参数
params = {
    'cat_smooth': 8,
    'is_unbalance': True,
    'max_depth': 9,
    'metric': ['binary_logloss', 'auc'],
    'min_child_samples': 22,
    'num_iterations': 200,
    'num_leaves': 100,
    'objective': 'binary',
    'reg_alpha': 0.01,
    'reg_lambda': 8,
    'early_stopping_rounds': 10
}

# 训练模型
model = lgb.train(params, train_data, valid_sets=[test_data])


print(model.best_iteration)
model.save_model('1.pkl')
# 预测
y_pred = model.predict(x_test, num_iteration=model.best_iteration)

# 评估模型性能
auc = roc_auc_score(y_test, y_pred)

print(f'AUC: {auc}')

D:\pycharm project\Internet-of-Vehicles-Collision-Recognition\venv\lib\site-packages\lightgbm\engine.py:172: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


[LightGBM] [Info] Number of positive: 26237, number of negative: 134210
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007539 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 968
[LightGBM] [Info] Number of data points in the train set: 160447, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.163524 -> initscore=-1.632235
[LightGBM] [Info] Start training from score -1.632235
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[6]	valid_0's binary_logloss: 0.37592	valid_0's auc: 0.871235
6
AUC: 0.8712353690384872


In [279]:
import pandas as pd

# 创建一个示例DataFrame
data = {'col1': [1, 2, 3, 4],
        'col2': ['A', 'B', 'C', 'D'],
        'col3': ['X', 'Y', 'Z', 'W']}

df = pd.DataFrame(data)

# 将DataFrame的第3列以及之后的列转换为整数类型
df.iloc[:, 2:] = df.iloc[:, 2:].astype(int)

# 打印转换后的DataFrame
print(df)


ValueError: invalid literal for int() with base 10: 'X'